"""Add system interface summaries

Revision ID: 0d2764bf7d04
Revises: 31af012caeb8
Create Date: 2026-02-21 06:37:26.273549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2764bf7d04'
down_revision: Union[str, Sequence[str], None] = '31af012caeb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_interface_daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('bytes_recv', sa.BigInteger(), nullable=True),
    sa.Column('packets_sent', sa.BigInteger(), nullable=True),
    sa.Column('packets_recv', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_interface_daily_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_interface_daily_summaries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_interface_daily_summaries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_interface_daily_summaries_interface'), ['interface'], unique=False)

    op.create_table('system_interface_monthly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('bytes_recv', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_interface_monthly_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_interface_monthly_summaries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_interface_monthly_summaries_interface'), ['interface'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_interface_monthly_summaries_month'), ['month'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_interface_monthly_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_interface_monthly_summaries_month'))
        batch_op.drop_index(batch_op.f('ix_system_interface_monthly_summaries_interface'))
        batch_op.drop_index(batch_op.f('ix_system_interface_monthly_summaries_id'))

    op.drop_table('system_interface_monthly_summaries')
    with op.batch_alter_table('system_interface_daily_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_interface_daily_summaries_interface'))
        batch_op.drop_index(batch_op.f('ix_system_interface_daily_summaries_id'))
        batch_op.drop_index(batch_op.f('ix_system_interface_daily_summaries_date'))

    op.drop_table('system_interface_daily_summaries')
    # ### end Alembic commands ###
