"""Phase 6 Data Layer Updates

Revision ID: 31af012caeb8
Revises: 2eb64d488aab
Create Date: 2026-02-21 05:04:00.590148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31af012caeb8'
down_revision: Union[str, Sequence[str], None] = '2eb64d488aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_devices_organizations_organization_id', 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key('fk_devices_device_groups_group_id', 'device_groups', ['group_id'], ['id'])

    with op.batch_alter_table('speedtest_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_speedtest_results_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_speedtest_results_organizations_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('traffic_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_logs_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_logs_device_id'))

    with op.batch_alter_table('speedtest_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_speedtest_results_organizations_organization_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_speedtest_results_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_devices_device_groups_group_id', type_='foreignkey')
        batch_op.drop_constraint('fk_devices_organizations_organization_id', type_='foreignkey')

    # ### end Alembic commands ###
