"""Add_AgentNode_and_AgentMetric_models

Revision ID: d01d8eb39fe5
Revises: f6d55e2026dd
Create Date: 2026-02-23 16:25:33.923007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01d8eb39fe5'
down_revision: Union[str, Sequence[str], None] = 'f6d55e2026dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('api_key_hash', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('system_info', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_nodes_api_key_hash'), ['api_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nodes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nodes_organization_id'), ['organization_id'], unique=False)

    op.create_table('agent_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('cpu_pct', sa.Float(), nullable=True),
    sa.Column('mem_usage', sa.Float(), nullable=True),
    sa.Column('disk_usage', sa.Float(), nullable=True),
    sa.Column('net_rx', sa.BigInteger(), nullable=True),
    sa.Column('net_tx', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_metrics_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_metrics_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_agent_metrics_id'))
        batch_op.drop_index(batch_op.f('ix_agent_metrics_agent_id'))

    op.drop_table('agent_metrics')
    with op.batch_alter_table('agent_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_nodes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agent_nodes_id'))
        batch_op.drop_index(batch_op.f('ix_agent_nodes_api_key_hash'))

    op.drop_table('agent_nodes')
    # ### end Alembic commands ###
