"""Add MonitoredCertificate model

Revision ID: f6d55e2026dd
Revises: a410fd873645
Create Date: 2026-02-23 07:36:12.273459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d55e2026dd'
down_revision: Union[str, Sequence[str], None] = 'a410fd873645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('days_until_expiration', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_certificates_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitored_certificates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitored_certificates_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_column('ip_address')
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('monitored_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_certificates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_monitored_certificates_id'))
        batch_op.drop_index(batch_op.f('ix_monitored_certificates_domain'))

    op.drop_table('monitored_certificates')
    # ### end Alembic commands ###
