/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope & {
    __WB_MANIFEST: any;
};

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Handle Push Notifications
self.addEventListener('push', (event: PushEvent) => {
    if (!event.data) return;

    try {
        const payload = event.data.json();
        const { title, body, icon, data } = payload;

        event.waitUntil(
            self.registration.showNotification(title || 'StatSea Alert', {
                body: body || 'You have a new network alert.',
                icon: icon || '/icon-512.png',
                badge: '/icon-512.png',
                data: data || {},
                vibrate: [200, 100, 200],
                tag: 'statsea-alert'
            } as any)
        );
    } catch (err) {
        console.error('Error handling push event:', err);
    }
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
    event.notification.close();

    // Default URL to open if none provided
    const urlToOpen = event.notification.data?.url || '/';

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if ('url' in client && client.url === urlToOpen && 'focus' in client) {
                    return (client as WindowClient).focus();
                }
            }
            // Otherwise, open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen);
            }
        })
    );
});
